### ISSUE TITLE
Plugin and setup-python action don't seem to work together.

### ISSUE THREAD

**Issue by pauldruce** [please-build/python-rules#127]
Hello, I've hit an issue using please in GitHub actions. The plugin doesn't seem to use the Python version that is set up by the 'setup-python' action. It uses the version installed by default for the operating system instead. 

This is true even for this repository itself. I have created a fork and made the following changes:
- Added version 3.12 to the plugin.yml 
- Added a pytest (and the necessary BUILD item) with the following contents: 
   ```python
    import sys
    def test_python_version_is_expected():
        assert sys.version_info[0] == 3
        assert sys.version_info[1] == 12
   ```
This test fails for the 3.12 version as you can see in the image below: 

<img width="1025" alt="Screenshot 2024-02-14 at 00 27 02" src="https://github.com/please-build/python-rules/assets/30435358/6cf1e111-d06c-4786-bb65-ba14677a0efe">

It seems like the tests all use 3.10 rather than the versions setup by the setup-action.

**Comment by pauldruce** [comment]
Here is a Draft PR on my fork to show you the changes I've made to get to this point: https://github.com/pauldruce/please-python-rules/pull/1

**Comment by pauldruce** [comment]
And here is the action run that shows all the different versions are actually using just 3.10: https://github.com/pauldruce/please-python-rules/actions/runs/7894575599

**Comment by chrisnovakovic** [comment]
Good catch, thanks! This happens because `actions/setup-python` adds the interpreter's `bin` directory to `PATH` but the updated `PATH` isn't inherited by Please's build sandbox by default.

**Comment by chrisnovakovic** [comment]
Version >= 1.8.0 of the plugin should work under `actions/setup-python` with `python-version` set to any Python version supported upstream (currently >= 3.9). Thanks again for reporting this!
