### ISSUE TITLE
Incorrect evaluation of `@self`

### ISSUE THREAD

**Issue by samwestmoreland** [please-build/python-rules#28]
It's expected that `@self` as a subrepo reference (e.g. `@self//third_party/python:foo`) when inside a plugin build file should evaluate to the plugin itself, but currently the reference is evaluated in whatever subrepo the build file is being subincluded from, resulting in directories not being found etc.

**Comment by Tatskaari** [comment]
I think this should be moved to the Please repo as it's not really a bug with the plugin.
